name: Hassfest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
